rpc: "https://api.avax.network/ext/bc/C/rpc"
address: "0x0A50EE15688665C4bB98c802F5ee11fEc3DF0B80"
production_adresses: "keys_adresses.json"
start_time: "allowlistStartTime" #'publicSaleStartTime' #"allowlistStartTime"
mint_haste: 1
transaction_settings: 
  is_wl: True
  count: 1
  gas: 300000
  max_fee: 300 #2000
  max_priority_fee: 50 #2000
  value: 0