rpc: "https://api.avax.network/ext/bc/C/rpc"
address: "0x974185e20aBBf0cdb4Dde67FbCFE245CA42fBAB1"
production_adresses: "keys_adresses.json"
start_time: "publicSaleStartTime" #'publicSaleStartTime' #"allowlistStartTime"
mint_haste: 1
transaction_settings: 
  is_wl: False
  count: 1
  gas: 300000
  max_fee: 2000 #2000
  max_priority_fee: 2000 #2000
  value: 5000000000000000000