rpc: "https://api.avax.network/ext/bc/C/rpc"
address: "0xF3b5903c277eF3d0c9679Bae3A2bf05D2CbA3441"
production_adresses: "keys_adresses.json"
start_time: 'publicSaleStartTime' #"allowlistStartTime"
mint_haste: 1
transaction_settings: 
  is_wl: False
  count: 1
  gas: 300000
  max_fee: 2000
  max_priority_fee: 2000
  value: 3000000000000000000